$script:extraCatalog=[ordered]@{
 timetable=@{name='시간표';width=640;height=650;body='<Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><Grid Margin="0,0,0,14"><Grid.ColumnDefinitions><ColumnDefinition/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><TextBlock x:Name="NextClass" Text="나의 다음 수업" FontSize="14" TextWrapping="Wrap"/><Button x:Name="NextClassLink" Grid.Column="1" Content="수업 링크 ↗" Padding="6,4"/></Grid><ScrollViewer Grid.Row="1" VerticalScrollBarVisibility="Hidden" HorizontalScrollBarVisibility="Disabled"><Grid x:Name="TimetableGrid"/></ScrollViewer><StackPanel Grid.Row="2" Orientation="Horizontal" HorizontalAlignment="Right" Style="{StaticResource QuietTools}" Margin="0,12,0,0"><Button x:Name="TimetableEdit" Content="시간표 편집"/></StackPanel></Grid>'}
 youtube=@{name='YouTube';width=560;height=500;body='<Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><Grid x:Name="YouTubeEntry" Style="{StaticResource QuietHoverEntry}" Margin="0,0,0,12"><Grid.ColumnDefinitions><ColumnDefinition/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><TextBox x:Name="YouTubeUrl" ToolTip="YouTube 영상·재생목록 링크 · Enter로 재생" Padding="12,9"/><Button x:Name="YouTubeOpen" Grid.Column="1" Content="재생" Margin="8,0,0,0" Padding="16,8"/></Grid><Border x:Name="YouTubeFrame" Grid.Row="1" Background="#0B101B" CornerRadius="14" ClipToBounds="True" MinHeight="200" MinWidth="200"><Grid x:Name="YouTubeViewHost"><StackPanel x:Name="YouTubePlaceholder" HorizontalAlignment="Center" VerticalAlignment="Center"><TextBlock Text="▶" Foreground="#A3E8D2" FontSize="40" HorizontalAlignment="Center"/><TextBlock Text="나만의 작은 영화관" FontSize="17" Foreground="#E9EDF5" Margin="0,16,0,8" HorizontalAlignment="Center"/><TextBlock Text="영상이나 재생목록 링크를 넣어보세요" FontSize="11" Foreground="#A9B6CA"/></StackPanel></Grid></Border><TextBlock x:Name="YouTubeStatus" Grid.Row="2" Text="YouTube · 위젯 안에서 바로 재생" FontSize="11" TextTrimming="CharacterEllipsis" Margin="2,12,2,8"/><StackPanel Grid.Row="3" Style="{StaticResource QuietTools}"><Grid><StackPanel Orientation="Horizontal"><Button x:Name="YouTubePrevious" Content="⏮" ToolTip="이전 영상" Padding="10,5"/><Button x:Name="YouTubeToggle" Content="▶" ToolTip="재생·일시정지" Margin="6,0" Padding="16,5"/><Button x:Name="YouTubeNext" Content="⏭" ToolTip="다음 영상" Padding="10,5"/></StackPanel><StackPanel Orientation="Horizontal" HorizontalAlignment="Right" VerticalAlignment="Center"><TextBlock Text="♪" FontSize="15" VerticalAlignment="Center"/><Slider x:Name="YouTubeVolume" Minimum="0" Maximum="100" Value="70" Width="90" Margin="8,0" ToolTip="볼륨"/><Button x:Name="YouTubeLogin" Content="↗" ToolTip="공식 사이트에서 열기" Padding="8,5"/></StackPanel></Grid></StackPanel></Grid>'}
 dday=@{name='D-day';width=330;height=330;body='<StackPanel><TextBlock x:Name="DdayNumber" Text="D−0" FontSize="62" FontWeight="Light"/><TextBlock x:Name="DdayTitle" Text="중요한 날을 등록하세요" TextWrapping="Wrap"/><TextBlock x:Name="DdayDate" FontSize="11" Margin="0,8,0,12"/><ComboBox x:Name="DdayChoice" Style="{StaticResource QuietSelect}" ToolTip="표시할 마감 선택"/><TextBlock x:Name="DdayHint" FontSize="10" TextWrapping="Wrap" Margin="0,10,0,0"/></StackPanel>'}
 habits=@{name='습관';width=360;height=390;body='<Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><TextBlock Text="작은 습관, 매일 한 번" FontSize="18" Margin="0,0,0,14"/><StackPanel x:Name="HabitRows" Grid.Row="1"/><TextBlock x:Name="HabitHint" Grid.Row="2" Text="최근 7일 · 체크하면 오늘의 기록이 남습니다" FontSize="10" TextWrapping="Wrap"/></Grid>'}
 media=@{name='지금 재생 중';width=380;height=320;body='<Grid><Grid.RowDefinitions><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><Grid><Grid.ColumnDefinitions><ColumnDefinition Width="106"/><ColumnDefinition/></Grid.ColumnDefinitions><Border CornerRadius="14" Background="#18FFFFFF" Width="96" Height="96" VerticalAlignment="Center"><Grid><TextBlock x:Name="MediaPlaceholder" Text="♫" FontSize="46" HorizontalAlignment="Center" VerticalAlignment="Center"/><Image x:Name="MediaArt" Stretch="UniformToFill"/></Grid></Border><StackPanel Grid.Column="1" VerticalAlignment="Center" Margin="8,0,0,0"><TextBlock x:Name="MediaTitle" Text="음악을 재생해보세요" FontSize="18" TextWrapping="Wrap" MaxHeight="80"/><TextBlock x:Name="MediaArtist" TextWrapping="Wrap" Margin="0,8,0,0" FontSize="11"/><TextBlock x:Name="MediaHint" Text="Windows 미디어 정보를 지원하는 앱" TextWrapping="Wrap" FontSize="10" Margin="0,8,0,0"/></StackPanel></Grid><StackPanel Grid.Row="1" Style="{StaticResource QuietTools}" Orientation="Horizontal" HorizontalAlignment="Center" Margin="0,12,0,0"><Button x:Name="MediaPrevious" Content="⏮"/><Button x:Name="MediaToggle" Content="▶" Margin="8,0"/><Button x:Name="MediaNext" Content="⏭"/></StackPanel></Grid>'}
 launcher=@{name='빠른 실행';width=350;height=340;body='<Grid><Grid.RowDefinitions><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><WrapPanel x:Name="LaunchItems"/><TextBlock x:Name="LaunchHint" Grid.Row="1" Text="앱 · 폴더 · 사이트를 내 방식대로" FontSize="10" TextWrapping="Wrap"/></Grid>'}
 progress=@{name='진행률';width=350;height=380;body='<Grid><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><TextBlock Text="조금씩, 끝까지" FontSize="20" Margin="0,0,0,14"/><StackPanel x:Name="ProgressRows" Grid.Row="1"/><TextBlock Grid.Row="2" Text="책 페이지 · 강의 수 · 프로젝트 단계" FontSize="10" TextWrapping="Wrap"/></Grid>'}
 system=@{name='시스템';width=340;height=350;body='<StackPanel><TextBlock x:Name="SystemCpu" Text="CPU —" FontSize="28"/><Canvas x:Name="SystemChart" Height="48" ClipToBounds="True" Margin="0,12,0,12"><Polyline x:Name="CpuLine" Stroke="#A3E8D2" StrokeThickness="2"/></Canvas><TextBlock x:Name="SystemMemory" Text="메모리 —" FontSize="16"/><ProgressBar x:Name="MemoryBar" Maximum="100" Height="4" Margin="0,10,0,16"/><TextBlock x:Name="SystemBattery" Text="배터리 —"/><TextBlock x:Name="SystemDisk" FontSize="11" Margin="0,12,0,0"/><TextBlock x:Name="SystemHint" Text="10초마다 갱신" FontSize="10" Margin="0,10,0,0"/></StackPanel>'}
 photo=@{name='사진·아트';width=340;height=380;body='<Grid><Grid.RowDefinitions><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><Grid><TextBlock x:Name="PhotoPlaceholder" Text="나의 작은 갤러리&#10;설정에서 사진을 선택하세요" TextWrapping="Wrap" HorizontalAlignment="Center" VerticalAlignment="Center"/><Image x:Name="PhotoImage" Stretch="Uniform"/></Grid><Grid Grid.Row="1" Margin="0,10,0,0"><TextBlock x:Name="PhotoCaption" FontSize="10" TextTrimming="CharacterEllipsis"/><StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Style="{StaticResource QuietTools}"><Button x:Name="PhotoPrev" Content="‹"/><Button x:Name="PhotoNext" Content="›"/></StackPanel></Grid></Grid>'}
 quote=@{name='오늘의 문장';width=360;height=300;body='<Grid><Grid.RowDefinitions><RowDefinition/><RowDefinition Height="Auto"/></Grid.RowDefinitions><TextBlock x:Name="QuoteText" Text="작은 한 걸음도 앞으로 가는 길입니다." FontSize="25" FontWeight="Light" TextWrapping="Wrap" VerticalAlignment="Center"/><Grid Grid.Row="1"><TextBlock x:Name="QuoteAuthor" FontSize="11" VerticalAlignment="Center"/><Button x:Name="QuoteNext" Content="다른 문장 ↻" HorizontalAlignment="Right" Style="{StaticResource QuietAction}"/></Grid></Grid>'}
}
$script:widgetDefaults=@{}; foreach($key in $widgets.Keys) {$widgetDefaults[$key]=@($widgets[$key].Width,$widgets[$key].Height)}
$newControls=New-Object Windows.Controls.StackPanel
$label=New-Object Windows.Controls.TextBlock; $label.Text='추가 위젯'; $label.FontSize=12; $label.Foreground='#A3E8D2'; $label.Margin='0,16,0,12'; [void]$newControls.Children.Add($label)
foreach($key in $extraCatalog.Keys) {
    $info=$extraCatalog[$key]; $widgets[$key]=New-Widget $key $info.name $info.width $info.height $info.body
    $widgets[$key].Topmost=$false; $widgets[$key].MinWidth=300; if($key -eq 'youtube') {$widgets[$key].MinWidth=420}; $minimums=@{timetable=420;youtube=460;dday=300;habits=250;media=270;launcher=240;progress=280;system=350;photo=240;quote=260}; $widgets[$key].MinHeight=$minimums[$key]
    $widgetDefaults[$key]=@($info.width,$info.height)
    if(-not $state.ContainsKey($key+'Visible')) {$state[$key+'Visible']=$false}
    $toggle=New-Object Windows.Controls.CheckBox; $toggle.Name='Show'+(Get-Culture).TextInfo.ToTitleCase($key); $toggle.Content=$info.name; $toggle.Margin='0,0,0,12'; [void]$newControls.Children.Add($toggle)
    $item=New-Object Windows.Controls.ComboBoxItem; $item.Content=$info.name; $item.Tag=$key; [void]$settingsWindow.FindName('StyleTarget').Items.Add($item)
}
[void]$settingsWindow.FindName('ExtraWidgetVisibility').Children.Add($newControls)
